title: ChaejinE
description: ML/AI Software Developer
site_title: '@cjlotto - Chaejin Jeong'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: ChaejinE
blog_url: https://velog.io/@lottocomeon
email: joung6517@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/cj.jpg

# Google Analytics ID
google_analytics: 